---
- name: Configure Join Commands on Master Node
  block:
    - name: Retrieve Join Command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set Join Command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

    
- name: Ensure kube_worker user exists with home directory
  ansible.builtin.user:
    name: kube_worker
    state: present
    shell: /bin/bash
    create_home: yes
    home: /home/kube_worker

- name: Join Worker Nodes
  block:
    - name: Enable TCP port 6443 (On Master) is able to connect from Worker
      wait_for: "host=69.164.221.35 port=6443 timeout=1"

    - name: Join worker to cluster
      shell: "{{ hostvars['69.164.221.35'].join_command }} >> node_joined.log"
      args:
        chdir: /home/kube_worker
        creates: node_joined.log
