---
- name: Create .kube directory
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: Copy config file to target host
  copy:
    src: /tmp/config
    dest: ~/.kube/config

- name: Configure Join Commands on Master Node
  block:
    - name: Retrieve Join Command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set Join Command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"
    
- name: Ensure kube_worker user exists with home directory
  ansible.builtin.user:
    name: kube_worker
    state: present
    shell: /bin/bash
    create_home: yes
    home: /home/kube_worker

- name: Display the custom fact
  ansible.builtin.debug:
    var: join_command

- name: Join Worker Nodes
  block:
    - name: Ensure TCP port 6443 (On Master) is able to connect from Worker
      wait_for: "host=66.228.41.195 port=6443 timeout=1"

        #    - name: Join worker to cluster
        #      host: kube-master
        #      become: yes
        #      block:

- name: run the damn play
  shell: "{{ join_command }} >> node_joined.log"
  args:
    chdir: /home/kube_worker
    creates: node_joined.log

- name: Ensure metallb port is open
  ansible.posix.firewalld:
    port: 7946/tcp
    permanent: true
    state: enabled
    immediate: true

- name: Ensure 7946/udp is open
  ansible.posix.firewalld:
    port: 7946/udp
    permanent: true
    state: enabled
    immediate: true

- name: Ensure kube api port is open
  ansible.posix.firewalld:
    port: 10250/tcp
    permanent: true
    state: enabled
    immediate: true

- name: Ensure kube proxy port is open
  ansible.posix.firewalld:
    port: 10256/tcp
    permanent: true
    state: enabled
    immediate: true

- name: Ensure NodePort TCP service ports are open
  ansible.posix.firewalld:
    port: 30000-32767/tcp
    permanent: true
    state: enabled
    immediate: true

- name: Ensure NodePort UDP service ports are open
  ansible.posix.firewalld:
    port: 30000-32767/udp
    permanent: true
    state: enabled
    immediate: true
