---
- name: Initialize Kubernetes Master
  block:
    - name: Copy kubeadm-config.yaml file
      copy:
        src: kubeadm-config.yaml
        dest: /etc/kubernetes/kubeadm-config.yaml
    
    - name: Ensure kube_admin user exists with home directory
      ansible.builtin.user:
        name: kube_admin
        state: present
        shell: /bin/bash
        create_home: yes
        home: /home/kube_admin

    - name: Ensure containerd group exists
      group:
        name: containerd
        state: present

    - name: Add user to containerd group
      user:
        name: kube_admin
        groups: containerd
        append: yes

    - name: Create systemd override directory for containerd
      file:
        path: /etc/systemd/system/containerd.service.d
        state: directory
        mode: '0755'

    - name: Override containerd socket permissions
      copy:
        dest: /etc/systemd/system/containerd.service.d/override.conf
        content: |
          [Service]
          ExecStartPost=/bin/bash -c 'chmod 0660 /run/containerd/containerd.sock && chown root:containerd /run/containerd/containerd.sock'
    
    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot:
    
        #    - name: Restart specific_service
          #      ansible.builtin.systemd:
          #        name: containerd.service  # Replace with the actual service name
          #        state: restarted
          ###############fix permissions

    - name: Disable Swap
      shell: swapoff -a
  
    - name: Ensure log-reader group exists
      group:
        name: log-reader
        state: present

    - name: Add user to log-reader group
      user:
        name: kube_admin
        groups: log-reader
        append: yes

    - name: Set group ownership on pod log directory
      file:
        path: /var/log/pods
        group: log-reader
        recurse: yes
        state: directory

    - name: Set read+execute permissions for group
      file:
        path: /var/log/pods
        mode: '0750'
        recurse: yes

    - name: Initialize the cluster
      shell: kubeadm init --config /etc/kubernetes/kubeadm-config.yaml >> cluster_initialized.log
      args:
        chdir: /home/kube_admin
        creates: cluster_initialized.log

    - name: Create .kube directory
      become_user: kube_admin
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Copy admin.conf to User's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/kube_admin/.kube/config
        remote_src: yes
        owner: kube_admin
        group: kube_admin

    - name: Install Pod Network
      become_user: kube_admin
      shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.log
      args:
        chdir: $HOME
        creates: pod_network_setup.log

    - name: Ensure firewalld is running and port 8080/tcp is open
      ansible.posix.firewalld:
        port: 6443/tcp
        permanent: true
        state: enabled
        immediate: true

### run kubelet containers at restart
