---
- name: Fix containerd CRI plugin for Kubernetes
  block:
    - name: Generate default containerd config
      ansible.builtin.command: containerd config default
      register: containerd_config

    - name: Write containerd config with CRI enabled
      ansible.builtin.copy:
        dest: /etc/containerd/config.toml
        content: "{{ containerd_config.stdout }}"
        owner: root
        group: root
        mode: '0644'

    - name: Patch containerd config for CRI and systemd cgroups
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^disabled_plugins =.*'
        line: '# disabled_plugins = []'
        state: present

    - name: Ensure runtime_type is io.containerd.runc.v2
      ansible.builtin.replace:
        path: /etc/containerd/config.toml
        regexp: 'runtime_type = "io.containerd.runc.v1"'
        replace: 'runtime_type = "io.containerd.runc.v2"'

    - name: Enable SystemdCgroup
      ansible.builtin.replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'

    - name: Restart containerd
      ansible.builtin.systemd:
        name: containerd
        state: restarted
        enabled: yes

